--VIEWS

CREATE VIEW EnrollmentDetails AS
SELECT E.SID, S.name AS student_name, S.email AS student_email, R.RID as Room_Number, T.name AS trainer_name, T.email AS trainer_email, C.course_name, C.start_date, C.end_date
FROM ENROLLS E
JOIN STUDENT S ON E.SID = S.SID
JOIN TRAINED_BY TB ON E.SID = TB.SID
JOIN TRAINER T ON TB.TID = T.TID
JOIN COURSE C ON E.CID = C.CID
JOIN ROOM R ON R.RID=C.RID;
SELECT * FROM EnrollmentDetails;

CREATE VIEW TrainerCourseDetails AS
SELECT S.name, T.TID, T.name AS trainer_name, T.email AS trainer_email, C.course_name, C.duration, C.start_date, C.end_date
FROM TRAINED_BY TB
JOIN TRAINER T ON TB.TID = T.TID
JOIN STUDENT S ON S.SID = TB.SID
JOIN ENROLLS E ON E.SID = S.SID
JOIN COURSE C ON C.CID = E.CID;
SELECT * FROM TrainerCourseDetails;

CREATE VIEW StudentCourseDetails AS
SELECT E.SID, S.name AS student_name, S.email AS student_email, C.course_name, C.duration, C.start_date, C.end_date
FROM ENROLLS E
JOIN STUDENT S ON E.SID = S.SID
JOIN COURSE C ON E.CID = C.CID;
SELECT * FROM StudentCourseDetails;


--TRIGGERS

--CREATION OF TRIGGERS

CREATE TRIGGER students_added
AFTER INSERT
ON TRAINED_BY
FOR EACH ROW
UPDATE TRAINER SET number_of_students = number_of_students + 1
WHERE TID IN(SELECT TID FROM TRAINED_BY WHERE TRAINER.TID=new.TID);

CREATE TRIGGER students_removed
AFTER DELETE
ON TRAINED_BY
FOR EACH ROW
UPDATE TRAINER SET number_of_students = number_of_students - 1
WHERE TID IN(SELECT TID FROM TRAINED_BY WHERE TRAINER.TID=old.TID);

CREATE TRIGGER yoga_mats_added
AFTER INSERT
ON ENROLLS
FOR EACH ROW
UPDATE ROOM SET yoga_mats = yoga_mats + 1
WHERE RID IN (SELECT RID FROM COURSE WHERE CID=new.CID);


--TESTING OF TRIGGER RESULTS

INSERT INTO STUDENT VALUES (116,'Bharath K',21,'bharath@gmail.com','8988565566','male','2002-01-08',1,88);
INSERT INTO TRAINED_BY VALUES (116,401);
SELECT * FROM STUDENT;
SELECT * FROM TRAINER;

INSERT INTO ENROLLS VALUES (116,301);
SELECT * FROM ROOM;

DELETE FROM TRAINED_BY WHERE SID=116;
SELECT * FROM TRAINER;

DELETE FROM ENROLLS WHERE SID=116;
DELETE FROM STUDENT WHERE SID=116;
SELECT * FROM STUDENT;

UPDATE ROOM SET yoga_mats=18 WHERE RID=201;


--DISPLAYING ALL TABLES AT THE END

SELECT * FROM STUDENT;
SELECT * FROM TRAINED_BY;
SELECT * FROM TRAINER;
SELECT * FROM ENROLLS;
SELECT * FROM COURSE;
SELECT * FROM ROOM;
SELECT * FROM MAINTENANCE;